server:
  port: 7001
spring:
  application:
    name: register-service
  profiles:
    active: dev

# MyBatis 配置
# MyBatis 配置
mybatis:
  #   - 配置Mybatis的Mapper文件
  mapper-locations: classpath:mybatis/mapper/*.xml
  #   - 配置Mybatis的实体目录
  type-aliases-package: com.example.registerservice.outlet.dao.mysql.po

#日志配置
logging:
  level:
    root: WARN
    com.example: DEBUG
  pattern:
    console: "${CONSOLE_LOG_PATTERN:\
      %clr(${LOG_LEVEL_PATTERN:%5p}) \
      %clr(|){faint} \
      %clr(%-40.40logger{39}){cyan} \
      %clr(:){faint} \
      %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"