# MyBatis 配置
mybatis:
  #   - 配置Mybatis的Mapper文件
  mapper-locations: classpath:mybatis/mapper/*.xml
  #   - 配置Mybatis的实体目录
  type-aliases-package: com.example.registerservice.outlet.dao.mysql.po
server:
  # 服务端口
  port: 7001
spring:
  application:
    # 应用名称
    name: register-service
  # 数据库配置
  datasource:
    #   - 配置数据库驱动：
    driver-class-name: com.mysql.cj.jdbc.Driver
    #   - 配置数据源名称
    name: defaultDataSource
    #   - 配置数据库用户名&密码：
    password: root
    username: root
    #   - 配置数据库连接地址
    url: jdbc:mysql://1.117.97.60:3307/h_register?serverTimezone=UTC
  # 消息队列配置
  rabbitmq:
    # rabbitmq服务器地址
    host: 1.117.97.60
    # rabbitmq服务器连接端口
    port: 5672
    virtual-host: /xiaoyu
    # rabbitmq服务器连接账号
    username: xiaoyu
    # rabbitmq服务器连接密码
    password: xiaoyu
  # Redis 配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 1.117.97.60
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最小空闲连接
        min-idle: 0
    # Redis服务器连接密码（默认为空）
    password: ''
    # Redis服务器连接端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 1000
  #spring-cloud的配置
  cloud:
    # nacos 配置
    nacos:
      discovery:
        namespace: public
        password: nacos
        server-addr: 192.172.0.160:8848
        username: nacos
        group: group3

#日志配置
logging:
  level:
    root: WARN
    com.example: DEBUG
  pattern:
    console: "${CONSOLE_LOG_PATTERN:\
      %clr(${LOG_LEVEL_PATTERN:%5p}) \
      %clr(|){faint} \
      %clr(%-40.40logger{39}){cyan} \
      %clr(:){faint} \
      %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"