server:
  port: 7001
spring:
  application:
    name: register-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        password: nacos
        username: nacos
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/h_register?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  rabbitmq:
    host: 127.0.0.1
    port: 5672
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: -1
        min-idle: 0
    timeout: 1000
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.example.registerservice.outlet.dao.mysql.po
