spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: root
    url: jdbc:mysql://1.117.97.60:3307/h_worker?serverTimezone=UTC
    username: root
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    password: evqkusxpybymdjhf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    username: 2592590720@qq.com
  rabbitmq:
    host: 1.117.97.60
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
    password: xiaoyu
    port: 5672
    username: xiaoyu
    virtual-host: /xiaoyu
  redis:
    database: 0
    host: 1.117.97.60
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: -1
        min-idle: 0
    password: xiaoyu
    port: 6379
    timeout: 1000

