spring:
  datasource:
    name: defaultDataSource
    url: jdbc:mysql://192.172.0.163:3307/hospital_four?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
