spring:
  datasource:
    name: defaultDataSource
    url: jdbc:mysql://1.117.97.60:3307/hospital_four?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
