server:
  port: 9100
spring:
  application:
    name: worker-service
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.example.workerservice.outlet.dao.mysql.po
