spring:
    application:
        name: outpatient-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        name: defaultDataSource
        password: root
        url: jdbc:mysql://1.117.97.60:3307/h_outpatient?serverTimezone=UTC
        username: root
        # 消息队列配置
    rabbitmq:
         # rabbitmq服务器地址
        host: 1.117.97.60
        # rabbitmq服务器连接端口
        port: 5672
        virtual-host: /xiaoyu
        # rabbitmq服务器连接账号
        username: xiaoyu
        # rabbitmq服务器连接密码
        password: xiaoyu
    cloud:
        nacos:
            discovery:
                group: group3
                namespace: public
                password: nacos
                #                server-addr: 192.172.0.160:8848
                server-addr: 127.0.0.1:8848
                username: nacos

server:
    port: 8081
mybatis:
    mapper-locations: classpath:/mybatis/mapper/*.xml
