version: '3'
services:
  gateway-server:
    build:
      context: $PWD/cloud-hospital-gateway-server
      dockerfile: Dockerfile
      args:
        JAR_FILE: cloud-hospital-gateway-server.jar
    image: gateway-server
    container_name: gateway-server-9527
    environment:
      - "JAVA_OPTS=-Xms512m -Xmx512m -Xmn256m"
    network_mode: "host"
    command: "--server.port=9527 --spring.profiles.active=pro"

  drug-service:
    build:
      context: $PWD/cloud-hospital-nacos-parent/drug-service
      dockerfile: Dockerfile
      args:
        JAR_FILE: drug-service.jar
    image: drug-service
    container_name: drug-service-8080
    mem_limit: 512m
    environment:
      - "JAVA_OPTS=-Xms512m -Xmx512m -Xmn256m"
    network_mode: "host"
    command: "--server.port=8080 --spring.profiles.active=pro"

  outpatient-service:
    build:
      context: $PWD/cloud-hospital-nacos-parent/outpatient-service
      dockerfile: Dockerfile
      args:
        JAR_FILE: outpatient-service.jar
    image: outpatient-service-8081
    container_name: outpatient-service
    mem_limit: 512m
    environment:
      - "JAVA_OPTS=-Xms512m -Xmx512m -Xmn256m"
    network_mode: "host"
    command: "--server.port=8081 --spring.profiles.active=pro"

  pay-service:
    build:
      context: $PWD/cloud-hospital-nacos-parent/pay-service
      dockerfile: Dockerfile
      args:
        JAR_FILE: pay-service.jar
    image: pay-service
    container_name: pay-service-8082
    mem_limit: 512m
    environment:
      - "JAVA_OPTS=-Xms512m -Xmx512m -Xmn256m"
    network_mode: "host"
    command: "--server.port=8082 --spring.profiles.active=pro"

  physical-exam-service:
    build:
      context: $PWD/cloud-hospital-nacos-parent/physical-exam-service
      dockerfile: Dockerfile
      args:
        JAR_FILE: physical-exam-service.jar
    image: physical-exam-service
    container_name: physical-exam-service-8083
    mem_limit: 512m
    environment:
      - "JAVA_OPTS=-Xms512m -Xmx512m -Xmn256m"
    network_mode: "host"
    command: "--server.port=8083 --spring.profiles.active=pro"

  register-service:
    build:
      context: $PWD/cloud-hospital-nacos-parent/register-service
      dockerfile: Dockerfile
      args:
        JAR_FILE: register-service.jar
    image: register-service
    container_name: register-service-8084
    mem_limit: 512m
    environment:
      - "JAVA_OPTS=-Xms512m -Xmx512m -Xmn256m"
    network_mode: "host"
    command: "--server.port=8084 --spring.profiles.active=pro"

  take-number-service:
    build:
      context: $PWD/cloud-hospital-nacos-parent/take-number-service
      dockerfile: Dockerfile
      args:
        JAR_FILE: take-number-service.jar
    image: take-number-service
    container_name: take-number-service-8085
    mem_limit: 512m
    environment:
      - "JAVA_OPTS=-Xms512m -Xmx512m -Xmn256m"
    network_mode: "host"
    command: "--server.port=8085 --spring.profiles.active=pro"

  verification-code-service:
    build:
      context: $PWD/cloud-hospital-nacos-parent/verification-code-service
      dockerfile: Dockerfile
      args:
        JAR_FILE: verification-code-service.jar
    image: verification-code-service
    container_name: verification-code-service-8086
    mem_limit: 512m
    environment:
      - "JAVA_OPTS=-Xms512m -Xmx512m -Xmn256m"
    network_mode: "host"
    command: "--server.port=8086 --spring.profiles.active=pro"

  worker-service:
    build:
      context: $PWD/cloud-hospital-nacos-parent/worker-service
      dockerfile: Dockerfile
      args:
        JAR_FILE: worker-service.jar
    image: worker-service8087
    container_name: worker-service-8087
    mem_limit: 512m
    environment:
      - "JAVA_OPTS=-Xms512m -Xmx512m -Xmn256m"
    network_mode: "host"
    command: "--server.port=8087 --spring.profiles.active=pro"

