server:
  port: 6003
spring:
  application:
    name: pay-service
  datasource:
    #   - 配置数据库驱动：
    driver-class-name: com.mysql.cj.jdbc.Driver
    #   - 配置数据源名称
    name: defaultDataSource
    #   - 配置数据库用户名&密码：
    password: root
    username: root
    #   - 配置数据库连接地址
    url: jdbc:mysql://1.117.97.60:3307/h_pay?serverTimezone=UTC
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        password: nacos
        username: nacos
# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.payservice.outlet.dao.mysql.callproofdao.pojo
