server:
  port: 6001
spring:
  application:
    name: take-number-service
  profiles:
    active: dev

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.takenumberservice.outlet.dao.mysql.pojo








