## 应用名称
#spring.application.name=take-number-service
## 应用服务 WEB 访问端口
#server.port=6001


#spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
#spring.datasource.url=jdbc:mysql://1.117.97.60:3307/h_takenumber?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.max-wait=60000

# MyBatis 配置
mybatis:
  #   - 配置Mybatis的Mapper文件
  mapper-locations: classpath:mapper/*.xml
  #   - 配置Mybatis的实体目录
  type-aliases-package: com.example.takenumberservice.outlet.dao.mysql.pojo
server:
    # 服务端口
  port: 6001

spring:
  cloud:
   nacos:
    discovery:
     namespace: public
     password: nacos
     server-addr: 1.117.97.60:8848
     username: nacos
     group: group3
  datasource:
    #   - 配置数据库驱动：
    driver-class-name: com.mysql.cj.jdbc.Driver
    #   - 配置数据源名称
    name: defaultDataSource
    #   - 配置数据库用户名&密码：
    password: root
    username: root
    #   - 配置数据库连接地址
    url: jdbc:mysql://1.117.97.60:3307/h_takenumber?serverTimezone=UTC
  application:
    # 应用名称
    name: take-number-service