spring:
  datasource:
    url: jdbc:mysql://192.172.0.163:3306/h_takenumber?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    username: root
    password: 123456
  redis:
    host: 192.172.0.163
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: -1
        min-idle: 0
    timeout: 1000
  rabbitmq:
    host: 192.172.0.163
    port: 5672
    username: guest
    password: guest

